version: "3.8"

services:
  db:
    image: postgres:15
    container_name: postgres
    environment:
      POSTGRES_DB: crypto_wallet
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  app:
    build:
      context: .
    container_name: crypto-wallet-api
    depends_on:
      - db
    environment:
      SPRING_PROFILES_ACTIVE: dev
    ports:
      - "8080:8080"

volumes:
  pgdata: